[options]
admin_passwd = $pbkdf2-sha512$600000$S8m5l/Lee49RylkLoRQCYA$G87wRvoxggG6AuM84A67a.NkA3awcHlxpB9Yft91wN878Avm/aPIkBxdHXGpgOFne9UB8ECevnncZUva4ETb9g
db_host = False
db_port = False
db_user = soporte
db_password = False
addons_path = addons,customs_addons
default_productivity_apps = True
logfile = odoo.log

