[options]
admin_passwd = $pbkdf2-sha512$600000$HANASMn5vzdm7D1n7J0Tgg$3hoJb1z.23MS33vdeq9krQYwCq3T6DPNkXIuCltAM7GDiWkC.4dXuTbBV8vL4Gm.tKUWed9jeTu5DNdlv2iaZQ
db_host = False
db_port = False
db_user = soporte
db_password = False
addons_path = /home/soporte/odoo/odoo_19/addons
default_productivity_apps = True
logfile = /home/soporte/odoo/odoo_19/odoo.log

